name: email-cron
on:
  schedule:
    # Every Friday at 1:00 PM UTC-- 9 AM Eastern.
    - cron: '0 13 * * FRI'
  
  workflow_dispatch:
    
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Call Email Route
        run: |
          curl --request POST \
          --url 'https://www.tweetnewsletter.xyz/api/cron' \
          --header 'authorization: ${{ secrets.EMAIL_API_SECRET }}'
